### ISSUE TITLE
[Feature] Add sync_id to stg_fivetran_log__log

### ISSUE THREAD

**Issue by camcyr-at-brzwy** [fivetran/dbt_fivetran_log#78]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Add the `sync_id` field to the `stg_fivetran_log__log` model. This would be useful for quickly identifying which sync events are associated with.

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @camcyr-at-brzwy thanks so much for suggesting this feature request!

I think this would be a great addition to the package and I see the value of being able to leverage the `sync_id` in the log models. I noticed you are interested in contributing this feature! If you would like to open a PR to contribute this new field I would be happy to review your PR and work with you to integrate your contribution into the next release.

Let me know if this would be of interest to you. Otherwise, my team can work to fold this into an upcoming sprint.

**Comment by camcyr-at-brzwy** [comment]
Hey @fivetran-joemarkiewicz! Wanted to let you know that I just opened [this PR](https://github.com/fivetran/dbt_fivetran_log/pull/79) to make this change.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks so much @camcyr-at-brzwy! I will review your PR in our current sprint and will let you know if I have any comments or suggestions directly in your PR 😄

**Comment by fivetran-joemarkiewicz** [comment]
Thanks again for opening this feature ad contributing to the package! This feature is now live in the latest release of the package.

**Comment by camcyr-at-brzwy** [comment]
@fivetran-joemarkiewicz Awesome! Glad I could help out and super excited that this is live.
